spring:
  application:
   name: VehicleService
  api:
    version: v1
server:
  port: 8085
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/